# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output_row.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import feature_pb2 as feature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x10output_row.proto\x1a\rfeature.proto\"'\n\tOutputRow\x12\x1a\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x08.Featureb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "output_row_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_OUTPUTROW"]._serialized_start = 35
    _globals["_OUTPUTROW"]._serialized_end = 74
# @@protoc_insertion_point(module_scope)
