# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solver_type.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import feature_pb2 as feature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11solver_type.proto\x1a\rfeature.proto"8\n\nSolverType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\nparameters\x18\x02 \x03(\x0b\x32\x08.Featureb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "solver_type_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SOLVERTYPE"]._serialized_start = 36
    _globals["_SOLVERTYPE"]._serialized_end = 92
# @@protoc_insertion_point(module_scope)
